### ISSUE TITLE
На странице со статьями не вызывается поле поиска браузера при нажатии стандартного сочетания клавиш Ctrl+f.

### ISSUE THREAD

**Issue by RinatValiullov** [nin-jin/HabHub#49]
*Моя система:*

Microsoft Windows 10
Google Chrome Version 103.0.5060.114 (Official Build) (64-bit)

*Описание проблемы:*

На [странице со статьями](https://mol.hyoo.ru/#!author=nin-jin/repo=HabHub/article=48/section=articles) при нажатии сочетания клавиш  `Ctrl+f` для вызова поля стандартного поиска в браузере (при фокусе на странице статьи) перекидывает на встроенный в приложение поиск. Такое поведение смущает и сбивает с толку.

![GDMp0l9Oqj](https://user-images.githubusercontent.com/9755333/178166606-6450277b-9247-4512-b995-d44cfaaa7fca.gif)

*Предложение по улучшению UX:*

Назначить внутренний поиск на другое сочетание клавиш при фокусе на странице со статьёй. Обычно принято брать `Ctrl+k` или `/`. Унифицировать такое поведение на всех страницах, где присутствует внутренний поиск (см. *Примечание*). 

![image](https://user-images.githubusercontent.com/9755333/178166999-8c050954-0efe-4983-b02b-dd3e9516014d.png)

*Примечание:*

На [странице с примерами](https://mol.hyoo.ru/#!section=demos) такое поведение отсутствует. Всегда вызывается поле стандартного поиска браузера.

**Comment by nin-jin** [comment]
Так как у нас используется виртуализированный рендеринг, то стандартный поиск по странице становится бесполезен и [приходится реализовывать свой](https://mol.hyoo.ru/#!section=slides/slides=https%3A%2F%2Fnin-jin.github.io%2Fslides%2Fvirt%2F/slide=70). Добавил такое поведение и на странице с примерами.

**Comment by RinatValiullov** [comment]
Спасибо за пояснение. Проверил. Действительно, стандартным поиском не всё находится. Закрываю.
